#!/usr/bin/env bash

CHANGED=$(git diff-index --name-only HEAD --)
if [ ! -z $CHANGED ]
then
    echo
    echo "   >>>  YOU NEED TO COMMIT $CHANGED  <<<"
    echo
else
    git pull
    git push
    rsync -avrz --exclude="200?" --exclude="201[0-7]" --delete-excluded ~/Physics1/www/ howdy:www/physics1/
fi
